[package]
name = "distant-echo"
version = "0.1.0"
authors = ["Eduard Kyvenko <eduard.kyvenko@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.13"
tokio = { version = "0.2.20", features = ["full"] }
futures = "0.3"
log = "0.4"
pretty_env_logger = "0.4.0"